services:
  go_app:
    container_name: go_api
    build:
        context: .
        dockerfile: api/Dockerfile
    environment:
      DB_URL: "postgres://recipe:mypassword@go_db:5432/recipe_db?sslmode=disable"
    ports:
      - "8080:8080"
    depends_on:
      - go_db
    command: /bin/bash -c "goose -dir ./migrations postgres \"$$DB_URL\" up && ./api"

  go_db:
    container_name: go_db
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_USER=recipe
      - POSTGRES_DB=recipe_db
    ports:
      - "5431:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
